name: kfupm_sports
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore:
  shared_preferences:
  # the annotation package containing @riverpod
  uuid: ^4.5.1
  provider: ^6.1.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # a tool for running code generators
  build_runner:

  

flutter:
  uses-material-design: true

  assets:
    - assets/images/black.jpg
    - assets/images/football.jpeg
    - assets/images/volleyball.jpeg