name: kfupm_sports
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore:
  # the annotation package containing @riverpod
  riverpod_annotation:
  riverpod:
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # a tool for running code generators
  build_runner:
  # the code generator
  riverpod_generator:
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/