// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-wWavZzwe7W38zagDqxWMalqa_O5yKBc',
    appId: '1:1061948834192:web:0df953111ee97eba663315',
    messagingSenderId: '1061948834192',
    projectId: 'kfupm-sports',
    authDomain: 'kfupm-sports.firebaseapp.com',
    storageBucket: 'kfupm-sports.firebasestorage.app',
    measurementId: 'G-R40HDKGK4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFR_2O7tvR3VKYZMKoCGYHvUibh4P7YsU',
    appId: '1:1061948834192:android:4826168d2b9c94d4663315',
    messagingSenderId: '1061948834192',
    projectId: 'kfupm-sports',
    storageBucket: 'kfupm-sports.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAok0MtWexECHlexkgGqGTcRLE1pqQfoKw',
    appId: '1:1061948834192:ios:64997e9fc624b89b663315',
    messagingSenderId: '1061948834192',
    projectId: 'kfupm-sports',
    storageBucket: 'kfupm-sports.firebasestorage.app',
    iosBundleId: 'com.example.kfupmSports',
  );

}